apiVersion: v1
kind: Service
metadata:
  name: {{ include "cls-backend-application.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cls-backend-application.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    appProtocol: http
    name: http
  selector:
    {{- include "cls-backend-application.selectorLabels" . | nindent 4 }}